### ISSUE TITLE
Implement ADR on toggle-life-expectancy

### ISSUE THREAD

**Issue by robrap** [openedx/edx-toggles#284]
**TODO:** @robrap needs to complete write up of this ticket.

This ticket is for implementing [ADR 0005-toggle-life-expectancy.rst](https://github.com/edx/edx-toggles/blob/master/docs/decisions/0005-toggle-life-expectancy.rst). Please review for details.

**Implementation details:**

- [ ] Introduce `toggle_life_expectancy` annotation with values of "temporary" or "permanent".
- [ ] Introduce `toggle_permanent_justification` as a free-form annotation.
- [ ] Update existing annotated toggles with these new annotations. See additional notes for details.

**Additional Notes:**
- This requires working in the code-annotations code, toggles code and docs, linting, and other repos using annotations.
- When adding the new annotations, there are a number of adjustments we may want to make at once.
  - We may need to relax linting rules first. When we do this, we may want to move faster on this part.

**Comment by robrap** [comment]
**Note**: I'm happy to be a guide and reviewer if someone picks this up.

**Comment by Yagnesh1998** [comment]
assign me

**Comment by Yagnesh1998** [comment]
@robrap I will assign it myself and start working on it shortly after my one pending DEPR ticket will be completed is that makes sense.
